controllers/kurtilas_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

kurtilas = Blueprint("kurtilas", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@kurtilas.route('/')
def kurtilas_index():
    return render_template("kurtilas/index.html")

@kurtilas.route('/kompetensi/<kompetensi>')
def kurtilas_kompetensi(kompetensi):
    # TODO : Diperbaiki
    siswa = [
        ["4822","Demitri Saklitunov"],
        ["4826","Virgiawan Listanto"],
        ["4843","Sanny Aura Syahrani"],
        ["4839","Daniswara Zaidan Abhinaya"],
        ["4840","Devina Joelian Salsadillah"]
    ]
    return render_template("kurtilas/kompetensi.html", siswa=siswa, kompetensi=kompetensi)

controllers/mapel_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

mapel = Blueprint("mapel", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@mapel.route('/mapel')
def mapel_index():
    data = kurtilas_db.getMapel()
    return render_template("kurtilas/mapel/index.html", mapel=data)

@mapel.route('/mapel/lihat/<mapel>')
def mapel_lihat(mapel):
    data = kurtilas_db.getMapel(mapel=mapel)
    return render_template("kurtilas/mapel/lihat.html", mapel=mapel, data_mapel=data)

@mapel.route('/mapel/ubah/<mapel>')
def mapel_ubah(mapel):
    data = kurtilas_db.getMapel(mapel=mapel)
    return render_template("kurtilas/mapel/ubah.html", mapel=mapel, data_mapel=data)

@mapel.route('/mapel/tambah')
def mapel_tambah():
    # data = kurtilas_db.getMapel(mapel=mapel)
    return render_template("kurtilas/mapel/ubah.html", mapel="mapel_", data_mapel=None)

@mapel.route('/mapel/simpan', methods=['GET', 'POST'])
def mapel_simpan():
    data = {}
    if request.method == 'POST':
        data = postDataParser(request.form)
    kurtilas_db.saveMapel(data['mapel'][0], data, aksi="ubah")
    return "OK"

templates/kurtilas/mapel/index.html
{% extends "base/base_content.html" %}

{% block page_title %}Daftar Mata Pelajaran{% endblock %}

{% block page_header %}
    Daftar Mata Pelajaran
{% endblock %}

{% block page_content %}
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Mata Pelajaran</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in mapel -%}
                    <tr>
                        <td>
                            {{loop.index}}
                        </td>
                        <td>
                            {{item[0]}}
                        </td>
                        <td>
                            <a href="{{ url_for('mapel.mapel_lihat', mapel=item[0]) }}"><button class="btn btn-info">i</button></a>
                            <a href="#"><button class="btn btn-danger">d</button></a>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ url_for('mapel.mapel_tambah')}}"><button class="btn btn-success">Tambah Mata Pelajaran</button></a>

{% endblock %}

templates/kurtilas/mapel/lihat.html
{% extends "base/base_content.html" %}

{% block page_title %}Tambah Mata Pelajaran{% endblock %}

{% block page_header %}
    Tambah Mata Pelajaran
{% endblock %}

{% block page_content %}
        Mata pelajaran : {{mapel}}
        <br><br>
        <h6>Pengetahuan</h6>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm" id="tabel_pengetahuan">
                <thead>
                    <tr>
                        <th class="col-md-2">No KD</th>
                        <th>Kompetensi Dasar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data_mapel[0] %}
                        <tr>
                            <td>
                                {{item[0]}}
                            </td>
                            <td>
                                {{item[2]}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <br><br>

        <h6>Keterampilan</h6>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm" id="tabel_keterampilan">
                <thead>
                    <tr>
                        <th class="col-md-2">No KD</th>
                        <th>Kompetensi Dasar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data_mapel[1] %}
                        <tr>
                            <td>
                                {{item[0]}}
                            </td>
                            <td>
                                {{item[2]}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <br><br>
        <a href="{{url_for('mapel.mapel_ubah', mapel=mapel)}}"><button class="btn btn-secondary">Ubah</button></a>
        <a href="#"><button class="btn btn-danger">Hapus</button></a>
{% endblock %}

templates/kurtilas/mapel/ubah.html
{% extends "base/base_content.html" %}

{% block page_title %}Tambah Mata Pelajaran{% endblock %}

{% block page_header %}
    Tambah Mata Pelajaran
{% endblock %}

{% block page_content %}
    <form action="{% if data_mapel is not none %}../{% endif %}simpan" method="post">
        Mata pelajaran : <input type="text" name="mapel" value="{{mapel}}">
        <br><br>
        <h6>Pengetahuan</h6>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm" id="tabel_pengetahuan">
                <thead>
                    <tr>
                        <th class="col-md-2">No KD</th>
                        <th>Kompetensi Dasar</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data_mapel[0] %}
                    <tr>
                        <td>
                            <input type="text" name="p_nokd" pattern=[0-9\.]* value="{{item[0]}}" required>
                        </td>
                        <td>
                            <input type="text" name="p_kd" class="col-md-12" value="{{item[2]}}" required>
                        </td>
                        <td>
                            <button class="btn btn-danger" id="hapus">-</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <button class="btn btn-info" id="tambah_pengetahuan">Tambah</button>

        <br><br>

        <h6>Keterampilan</h6>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm" id="tabel_keterampilan">
                <thead>
                    <tr>
                        <th class="col-md-2">No KD</th>
                        <th>Kompetensi Dasar</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data_mapel[1] %}
                    <tr>
                        <td>
                            <input type="text" name="k_nokd" pattern=[0-9\.]* value="{{item[0]}}" required>
                        </td>
                        <td>
                            <input type="text" name="k_kd" class="col-md-12" value="{{item[2]}}" required>
                        </td>
                        <td>
                            <button class="btn btn-danger" id="hapus">-</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <button class="btn btn-info" id="tambah_keterampilan">Tambah</button>

        <br><br>
        <input type="submit" class="btn btn-success" value="Simpan">

    </form>
{% endblock %}

{% block script %}
    <script>
        $(document).on("click","#hapus",function(){
            $(this).parent().parent().remove();
        });

            $("#tambah_pengetahuan").click(function(){
                var row = '<tr>'
                +'    <td>'
                +'        <input type="text" name="p_nokd" pattern=[0-9\.]* required>'
                +'    </td>'
                +'    <td>'
                +'        <input type="text" name="p_kd" class="col-md-12" required>'
                +'    </td>'
                +'    <td>'
                +'        <button class="btn btn-danger" id="hapus">-</button>'
                +'    </td>'
                +'</tr>';
                $("#tabel_pengetahuan tbody").append(row);
                return false;
            })

            $("#tambah_keterampilan").click(function(){
            var row = '<tr>'
                +'    <td>'
                +'        <input type="text" name="k_nokd" pattern=[0-9\.]* required>'
                +'    </td>'
                +'    <td>'
                +'        <input type="text" name="k_kd" class="col-md-12" required>'
                +'    </td>'
                +'    <td>'
                +'        <button class="btn btn-danger" id="hapus">-</button>'
                +'    </td>'
                +'</tr>';
                $("#tabel_keterampilan tbody").append(row);
                return false;
            })
    </script>

{% endblock %}