controllers/kurtilas_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

kurtilas = Blueprint("kurtilas", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@kurtilas.route('/')
def kurtilas_index():
    return render_template("kurtilas/index.html")

@kurtilas.route('/kompetensi/<kompetensi>')
def kurtilas_kompetensi(kompetensi):
    # TODO : Diperbaiki
    siswa = [
        ["4822","Demitri Saklitunov"],
        ["4826","Virgiawan Listanto"],
        ["4843","Sanny Aura Syahrani"],
        ["4839","Daniswara Zaidan Abhinaya"],
        ["4840","Devina Joelian Salsadillah"]
    ]
    return render_template("kurtilas/kompetensi.html", siswa=siswa, kompetensi=kompetensi)

controllers/mapel_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

mapel = Blueprint("mapel", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@mapel.route('/mapel')
def mapel_index():
    data = kurtilas_db.getMapel()
    return render_template("kurtilas/mapel/index.html", mapel=data)

@mapel.route('/mapel/lihat/<mapel>')
def mapel_lihat(mapel):
    data = kurtilas_db.getMapel(mapel=mapel)
    return render_template("kurtilas/mapel/lihat.html", mapel=mapel, data_mapel=data)

@mapel.route('/mapel/ubah/<mapel>')
def mapel_ubah(mapel):
    data = kurtilas_db.getMapel(mapel=mapel)
    return render_template("kurtilas/mapel/ubah.html", mapel=mapel, data_mapel=data)

@mapel.route('/mapel/tambah')
def mapel_tambah():
    # data = kurtilas_db.getMapel(mapel=mapel)
    return render_template("kurtilas/mapel/ubah.html", mapel="mapel_", data_mapel=None)

@mapel.route('/mapel/simpan', methods=['GET', 'POST'])
def mapel_simpan():
    data = {}
    if request.method == 'POST':
        data = postDataParser(request.form)
    kurtilas_db.saveMapel(data['mapel'][0], data, aksi="ubah")
    return "OK"

controllers/siswa_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

siswa = Blueprint("siswa", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@siswa.route('/siswa')
@siswa.route('/siswa/lihat')
def siswa_index():
    siswa = kurtilas_db.getSiswa()
    return render_template("kurtilas/siswa/index.html", data_siswa=siswa)

@siswa.route('/siswa/tambah')
def siswa_tambah():
    data = [[]]
    for i in range(0,20): data[0].append(None)
    return render_template("kurtilas/siswa/ubah.html", data=data)

@siswa.route('/siswa/ubah/<nipd>')
def siswa_ubah(nipd):
    data = kurtilas_db.getSiswa(nipd=nipd)
    return render_template("kurtilas/siswa/ubah.html", data=data, ubah=True)

@siswa.route('/siswa/simpan', methods=['GET', 'POST'])
def siswa_simpan():
    data = []
    if request.method == 'POST':
        data = postDataParser(request.form)
    res = kurtilas_db.saveSiswa(data['data'], data['aksi'][0])
    if res:
        return "OK"
    else:
        return "NOK"

@siswa.route('/siswa/lihat/<nipd>')
def siswa_lihat(nipd):
    siswa = kurtilas_db.getSiswa(nipd=nipd)
    return render_template("kurtilas/siswa/lihat.html", data_siswa=siswa)

@siswa.route('/siswa/hapus/<nipd>')
def siswa_hapus(nipd):
    res = kurtilas_db.saveSiswa(data=nipd, aksi="hapus")
    if res:
        return "OK"
    else:
        return "NOK"

templates/kurtilas/index.html
{% extends "base/base_content.html" %}

{% block page_title %}PegelKurtilas{% endblock %}

{% block page_header %}
    PegelKurtilas
{% endblock %}

{% block page_content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Mata Pelajaran</h5>
            <div class="card-text">
                Periksa Mata Pelajaran disini!<br>
                <a href="{{ url_for('mapel.mapel_index') }}"><button class="btn btn-primary">Mata Pelajaran</button></a>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Daftar Siswa</h5>
            <div class="card-text">
                Periksa Daftar Siswa disini!<br>
                <a href="{{ url_for('siswa.siswa_index') }}"><button class="btn btn-primary">Daftar Siswa</button></a>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Nilai</h5>
            <div class="card-text">
                Beri penilaian disini!<br>
                <a href="{{ url_for('kurtilas.kurtilas_penilaian', jenis='pengetahuan', mapel='mapel_pkn') }}"><button class="btn btn-primary">Daftar Siswa</button></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/kurtilas/kompetensi.html
{% extends "base/base_content.html" %}

{% block page_title %}Kompetensi{% endblock %}

{% block page_header %}
    Penilaian Kompetensi Spiritual
{% endblock %}

{% block page_content %}

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Keterangan Kompetensi</h5>
            <div class="card-text">
                Beribadah : Ketaatan beribadah<br>
                Syukur : Berperilaku syukur<br>
                Berdoa :Berdoa sebelum dan sesudah melakukan kegiatan<br>
                Toleransi : Toleransi dalam beribadah<br>
            </div>
        </div>
    </div>

    <br>

    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th>No</th>
                    <th>NIPD</th>
                    <th>Nama</th>
                    <th>Beribadah</th>
                    <th>Syukur</th>
                    <th>Berdoa</th>
                    <th>Toleransi</th>
                </tr>
            </thead>
            <tbody>
                {% for item in siswa -%}
                    <tr>
                        <td>
                            {{loop.index}}
                        </td>
                        <td>
                            {{item[0]}}
                        </td>
                        <td>
                            {{item[1]}}
                        </td>
                        <td>
                            <input type="radio" name="k1[{{loop.index0}}]" value="SB"/>
                            <label>Sangat Baik</label>
                            <input type="radio" name="k1[{{loop.index0}}]" value="B" checked/>
                            <label>Baik</label>
                        </td>
                        <td>
                            <input type="radio" name="k2[{{loop.index0}}]" value="SB"/>
                            <label>Sangat Baik</label>
                            <input type="radio" name="k2[{{loop.index0}}]" value="B" checked/>
                            <label>Baik</label>
                        </td>
                        <td>
                            <input type="radio" name="k3[{{loop.index0}}]" value="SB"/>
                            <label>Sangat Baik</label>
                            <input type="radio" name="k3[{{loop.index0}}]" value="B" checked/>
                            <label>Baik</label>
                        </td>
                        <td>
                            <input type="radio" name="k4[{{loop.index0}}]" value="SB"/>
                            <label>Sangat Baik</label>
                            <input type="radio" name="k4[{{loop.index0}}]" value="B" checked/>
                            <label>Baik</label>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="#"><button class="btn btn-success">Tambah Siswa</button></a>

{% endblock %}