controllers/kurtilas_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

kurtilas = Blueprint("kurtilas", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@kurtilas.route('/')
def kurtilas_index():
    return render_template("kurtilas/index.html")

@kurtilas.route('/kompetensi/<kompetensi>')
def kurtilas_kompetensi(kompetensi):
    # TODO : Diperbaiki
    siswa = [
        ["4822","Demitri Saklitunov"],
        ["4826","Virgiawan Listanto"],
        ["4843","Sanny Aura Syahrani"],
        ["4839","Daniswara Zaidan Abhinaya"],
        ["4840","Devina Joelian Salsadillah"]
    ]
    return render_template("kurtilas/kompetensi.html", siswa=siswa, kompetensi=kompetensi)

controllers/siswa_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

siswa = Blueprint("siswa", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@siswa.route('/siswa')
@siswa.route('/siswa/lihat')
def siswa_index():
    siswa = kurtilas_db.getSiswa()
    return render_template("kurtilas/siswa/index.html", data_siswa=siswa)

@siswa.route('/siswa/tambah')
def siswa_tambah():
    data = [[]]
    for i in range(0,20): data[0].append(None)
    return render_template("kurtilas/siswa/ubah.html", data=data)

@siswa.route('/siswa/ubah/<nipd>')
def siswa_ubah(nipd):
    data = kurtilas_db.getSiswa(nipd=nipd)
    return render_template("kurtilas/siswa/ubah.html", data=data, ubah=True)

@siswa.route('/siswa/simpan', methods=['GET', 'POST'])
def siswa_simpan():
    data = []
    if request.method == 'POST':
        data = postDataParser(request.form)
    res = kurtilas_db.saveSiswa(data['data'], data['aksi'][0])
    if res:
        return "OK"
    else:
        return "NOK"

@siswa.route('/siswa/lihat/<nipd>')
def siswa_lihat(nipd):
    siswa = kurtilas_db.getSiswa(nipd=nipd)
    return render_template("kurtilas/siswa/lihat.html", data_siswa=siswa)

@siswa.route('/siswa/hapus/<nipd>')
def siswa_hapus(nipd):
    res = kurtilas_db.saveSiswa(data=nipd, aksi="hapus")
    if res:
        return "OK"
    else:
        return "NOK"

templates/kurtilas/siswa/index.html
{% extends "base/base_content.html" %}

{% block page_title %}Daftar Siswa{% endblock %}

{% block page_header %}
    Daftar Siswa
{% endblock %}

{% block page_content %}
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th>No</th>
                    <th>NIPD</th>
                    <th>NISN</th>
                    <th>Nama Lengkap</th>
                    <th>Jenis Kelamin</th>
                    <th>Tempat, Tanggal Lahir</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in data_siswa -%}
                    <tr>
                        <td>
                            {{loop.index}}
                        </td>
                        <td>
                            {{item[0]}}
                        </td>
                        <td>
                            {{item[1]}}
                        </td>
                        <td>
                            {{item[2]}}
                        </td>
                        <td>
                            {% if item[3]==0 %}
                            Laki-laki
                            {% else %}
                            Perempuan
                            {% endif %}
                        </td>
                        <td>
                            {{item[5]}}, {{item[6]}}
                        </td>
                        <td>
                            <a href="{{url_for('siswa.siswa_lihat', nipd=item[0])}}"><button class="btn btn-info">i</button></a>
                            <a href="{{url_for('siswa.siswa_ubah', nipd=item[0])}}"><button class="btn btn-secondary">e</button></a>
                            <a href="#"><button class="btn btn-danger">d</button></a>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{url_for('siswa.siswa_tambah')}}"><button class="btn btn-success">Tambah Siswa</button></a>

{% endblock %}

templates/kurtilas/siswa/lihat.html
{% extends "base/base_content.html" %}

{% block page_title %}Lihat Siswa{% endblock %}

{% block page_header %}
    Lihat Siswa
{% endblock %}

{% block page_content %}
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm">
            <tbody>
                <tr>
                    <td width="20%">Nama</td>
                    <td>{{data_siswa[0][2]}}</td>
                </tr>
                <tr>
                    <td>NIPD</td>
                    <td>{{data_siswa[0][0]}}</td>
                </tr>
                <tr>
                    <td>NISN</td>
                    <td>{{data_siswa[0][1]}}</td>
                </tr>
                <tr>
                    <td>Jenis Kelamin</td>
                    <td>{% if data_siswa[0][3]==0 %}Laki-laki{% else %}Perempuan{% endif %}</td>
                </tr>
                <tr>
                    <td>Agama</td>
                    <td>{{data_siswa[0][4]}}</td>
                </tr>
                <tr>
                    <td>Tempat, Tanggal Lahir</td>
                    <td>{{data_siswa[0][5]}}</td>
                </tr>
                <tr>
                    <td>Alamat</td>
                    <td>{{data_siswa[0][6]}}</td>
                </tr>
                <tr>
                    <td>No. Telepon Peserta Didik</td>
                    <td>{{data_siswa[0][7]}}</td>
                </tr>
                <tr>
                    <td>Pendidikan Sebelumnya</td>
                    <td>{{data_siswa[0][8]}}</td>
                </tr>
                <tr>
                    <td>Nama Ayah</td>
                    <td>{{data_siswa[0][9]}}</td>
                </tr>
                <tr>
                    <td>Nama Ibu</td>
                    <td>{{data_siswa[0][10]}}</td>
                </tr>
                <tr>
                    <td>Pekerjaan Ayah</td>
                    <td>{{data_siswa[0][11]}}</td>
                </tr>
                <tr>
                    <td>Pekerjaan Ibu</td>
                    <td>{{data_siswa[0][12]}}</td>
                </tr>
                <tr>
                    <td>Alamat Orang Tua</td>
                    <td>{{data_siswa[0][13]}}</td>
                </tr>
                <tr>
                    <td>No. Telepon Orang Tua</td>
                    <td>{{data_siswa[0][14]}}</td>
                </tr>
                <tr>
                    <td>Nama Wali</td>
                    <td>{{data_siswa[0][15]}}</td>
                </tr>
                <tr>
                    <td>Pekerjaan Wali</td>
                    <td>{{data_siswa[0][16]}}</td>
                </tr>
                <tr>
                    <td>Alamat Wali</td>
                    <td>{{data_siswa[0][17]}}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <a href="{{url_for('siswa.siswa_ubah', nipd=data_siswa[0][0])}}"><button class="btn btn-secondary">Ubah</button></a>
    <a href="{{url_for('siswa.siswa_hapus', nipd=data_siswa[0][0])}}"><button class="btn btn-danger">Hapus</button></a>

{% endblock %}

templates/kurtilas/siswa/ubah.html
{% extends "base/base_content.html" %}

{% block page_title %}Lihat Siswa{% endblock %}

{% block page_header %}
    Tambah Siswa
{% endblock %}

{% block page_content %}
<form action="{% if ubah %}../{% endif %}simpan" method="post">
    <input name="aksi" value="{% if ubah %}ubah{% else %}baru{% endif %}" type="hidden">
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm">
            <tbody>
                <tr>
                    <td width="20%">Nama</td>
                    <td><input type="text" name="data" value="{{data[0][2]}}" required></td>
                </tr>
                <tr>
                    <td>NIPD</td>
                    <td><input type="number" name="data" value="{{data[0][0]}}" required {% if ubah %}readonly{% endif %}></td>
                </tr>
                <tr>
                    <td>NISN</td>
                    <td><input type="number" name="data" value="{{data[0][1]}}" required></td>
                </tr>
                <tr>
                    <td>Jenis Kelamin</td>
                    <td>
                        <input type="radio" name="data" value="0" {% if data[0][3] == 0 %}selected{% endif %} />
                        <label>Laki-laki</label>
                        <input type="radio" name="data" value="1" {% if data[0][3] == 1 %}selected{% endif %}/>
                        <label>Perempuan</label>
                    </td>
                </tr>
                <tr>
                    <td>Agama</td>
                    <td><input type="text" name="data" value="{{data[0][4]}}" required></td>
                </tr>
                <tr>
                    <td>Tempat, Tanggal Lahir</td>
                    <td><input type="text" name="data" value="{{data[0][5]}}" required>
                    <input type="text" name="data" value="{{data[0][6]}}" required></td>
                </tr>
                <tr>
                    <td>Alamat</td>
                    <td><input type="text" name="data" value="{{data[0][7]}}" required></td>
                </tr>
                <tr>
                    <td>No. Telepon Peserta Didik</td>
                    <td><input type="text" name="data" value="{{data[0][8]}}"></td>
                </tr>
                <tr>
                    <td>Pendidikan Sebelumnya</td>
                    <td><input type="text" name="data" value="{{data[0][9]}}" required></td>
                </tr>
                <tr>
                    <td>Nama Ayah</td>
                    <td><input type="text" name="data" value="{{data[0][10]}}" required></td>
                </tr>
                <tr>
                    <td>Nama Ibu</td>
                    <td><input type="text" name="data" value="{{data[0][11]}}" required></td>
                </tr>
                <tr>
                    <td>Pekerjaan Ayah</td>
                    <td><input type="text" name="data" value="{{data[0][12]}}" required></td>
                </tr>
                <tr>
                    <td>Pekerjaan Ibu</td>
                    <td><input type="text" name="data" value="{{data[0][13]}}" required></td>
                </tr>
                <tr>
                    <td>Alamat Orang Tua</td>
                    <td><input type="text" name="data" value="{{data[0][14]}}" required></td>
                </tr>
                <tr>
                    <td>No. Telepon Orang Tua</td>
                    <td><input type="text" name="data" value="{{data[0][15]}}"></td>
                </tr>
                <tr>
                    <td>Nama Wali</td>
                    <td><input type="text" name="data" value="{{data[0][16]}}"></td>
                </tr>
                <tr>
                    <td>Pekerjaan Wali</td>
                    <td><input type="text" name="data" value="{{data[0][17]}}"></td>
                </tr>
                <tr>
                    <td>Alamat Wali</td>
                    <td><input type="text" name="data" value="{{data[0][18]}}"></td>
                </tr>
                <tr>
                    <td>No. Telepon Wali</td>
                    <td><input type="text" name="data" value="{{data[0][19]}}"></td>
                </tr>
            </tbody>
        </table>
    </div>

    <input type="submit" class="btn btn-success" value="Simpan">
</form>
{% endblock %}