controllers/kurtilas_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

kurtilas = Blueprint("kurtilas", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@kurtilas.route('/')
def kurtilas_index():
    return render_template("kurtilas/index.html")

@kurtilas.route('/kompetensi/<kompetensi>')
def kurtilas_kompetensi(kompetensi):
    # TODO : Diperbaiki
    siswa = [
        ["4822","Demitri Saklitunov"],
        ["4826","Virgiawan Listanto"],
        ["4843","Sanny Aura Syahrani"],
        ["4839","Daniswara Zaidan Abhinaya"],
        ["4840","Devina Joelian Salsadillah"]
    ]
    return render_template("kurtilas/kompetensi.html", siswa=siswa, kompetensi=kompetensi)

controllers/nilai_controller.py
from flask import Blueprint, render_template, request
from models import kurtilas_db

nilai = Blueprint("nilai", __name__)

def postDataParser(form):
    data = {}
    key = []
    for item in request.form.keys():
        key.append(item)
    for par in key:
        data[par] = form.getlist(par)
    return data

@nilai.route('/nilai')
def nilai_index():
    data = kurtilas_db.getMapel()
    return render_template("kurtilas/nilai/index.html", mapel=data)

@nilai.route('/nilai/<mapel>')
def nilai_lihat(mapel):
    pass

@nilai.route('/nilai/<mapel>/ubah')
def nilai_penilaian(mapel):
    data_mapel = kurtilas_db.getMapel(mapel=mapel)
    siswa = kurtilas_db.getSiswa()
    return render_template("kurtilas/nilai/ubah.html", siswa=siswa, mapel=mapel.split('_')[1], data_mapel=data_mapel)

@nilai.route('/nilai/<mapel>/simpan', methods=['GET', 'POST'])
def nilai_penilaian_simpan(mapel):
    if request.method == 'POST':
        data = postDataParser(request.form)
        # print(data)
        kurtilas_db.saveNilai(data, mapel)
    return "Check console"

templates/kurtilas/nilai/index.html
{% extends "base/base_content.html" %}

{% block page_title %}Lihat Penilaian{% endblock %}

{% block page_header %}
    Lihat Penilaian
{% endblock %}

{% block page_content %}
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Mata Pelajaran</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in mapel -%}
                    <tr>
                        <td>
                            {{loop.index}}
                        </td>
                        <td>
                            {{item[0]}}
                        </td>
                        <td>
                            <a href="{{ url_for('nilai.nilai_lihat', mapel=item[0]) }}">
                                <button class="btn btn-info">i</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

templates/kurtilas/nilai/lihat.html
{% extends "base/base_content.html" %}

{% block page_title %}Penilaian{% endblock %}

{% block page_header %}
    Penilaian
{% endblock %}

{% block page_content %}
    <h4>Mata Pelajaran : {{mapel}}</h4><br><br>

    <form action="simpan" method="post">
        <h5>Pengetahuan</h5>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm">
                <thead>
                    <tr>
                        <th rowspan="2">No</th>
                        <th rowspan="2">NIPD</th>
                        <th rowspan="2">Nama</th>
                        <th colspan="{{data_mapel[0]|length}}">Kompetensi Dasar</th>
                        <th colspan="4">Nilai</th>
                    </tr>
                    <tr>
                        {% for item in data_mapel[0] %}
                        <th>{{item[0]}}</th>
                        {% endfor %}
                        <th>Rata-rata</th>
                        <th>Predikat</th>
                        <th>Maksimal</th>
                        <th>Minimal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in siswa -%}
                        <tr>
                            <td>
                                {{loop.index}}
                            </td>
                            <td>
                                {{item[0]}}
                            </td>
                            <td>
                                {{item[2]}}
                            </td>
                            {% for kd in data_mapel[0] %}
                            <td>
                                <input type="number" name="{{item[0]}}" value="0"/>
                            </td>
                            {% endfor %}
                            <td>
                                0
                            </td>
                            <td>
                                D
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h5>Keterampilan</h5>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm">
                <thead>
                    <tr>
                        <th rowspan="2">No</th>
                        <th rowspan="2">NIPD</th>
                        <th rowspan="2">Nama</th>
                        <th colspan="{{data_mapel[1]|length}}">Kompetensi Dasar</th>
                        <th colspan="4">Nilai</th>
                    </tr>
                    <tr>
                        {% for item in data_mapel[1] %}
                        <th>{{item[0]}}</th>
                        {% endfor %}
                        <th>Rata-rata</th>
                        <th>Predikat</th>
                        <th>Maksimal</th>
                        <th>Minimal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in siswa -%}
                        <tr>
                            <td>
                                {{loop.index}}
                            </td>
                            <td>
                                {{item[0]}}
                            </td>
                            <td>
                                {{item[2]}}
                            </td>
                            {% for kd in data_mapel[1] %}
                            <td>
                                <input type="number" name="{{item[0]}}" value="0"/>
                            </td>
                            {% endfor %}
                            <td>
                                0
                            </td>
                            <td>
                                D
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <input type="submit" class="btn btn-success" value="Simpan">
    </form>

{% endblock %}

templates/kurtilas/nilai/ubah.html
{% extends "base/base_content.html" %}

{% block page_title %}Penilaian{% endblock %}

{% block page_header %}
    Penilaian
{% endblock %}

{% block page_content %}
    <!--<div class="card col-md-4">-->
        <!--<div class="card-body">-->
            <!--<h5 class="card-title">Pilih Penilaian</h5>-->
            <!--<div class="card-text">-->
                <!--Mata Pelajaran :-->
                <!--<select name="Mapel">-->
                    <!--<option value="pkn" selected>PKn</option>-->
                <!--</select>-->
                <!--Jenis :-->
                <!--<select name="Jenis">-->
                    <!--<option value="pengetahuan" selected>Pengetahuan</option>-->
                    <!--<option value="keterampilan">Keterampilan</option>-->
                <!--</select>-->
                <!--<a href="#"><button class="btn btn-primary">Beri Penilaian</button></a>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
    <!--<br><br>-->

    <h4>Mata Pelajaran : {{mapel}}</h4><br><br>

    <form action="simpan" method="post">
        <h5>Pengetahuan</h5>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm">
                <thead>
                    <tr>
                        <th rowspan="2">No</th>
                        <th rowspan="2">NIPD</th>
                        <th rowspan="2">Nama</th>
                        <th colspan="{{data_mapel[0]|length}}">Kompetensi Dasar</th>
                        <th colspan="4">Nilai</th>
                    </tr>
                    <tr>
                        {% for item in data_mapel[0] %}
                        <th>{{item[0]}}</th>
                        {% endfor %}
                        <th>Rata-rata</th>
                        <th>Predikat</th>
                        <th>Maksimal</th>
                        <th>Minimal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in siswa -%}
                        <tr>
                            <td>
                                {{loop.index}}
                            </td>
                            <td>
                                {{item[0]}}
                            </td>
                            <td>
                                {{item[2]}}
                            </td>
                            {% for kd in data_mapel[0] %}
                            <td>
                                <input type="number" name="{{item[0]}}" value="0"/>
                            </td>
                            {% endfor %}
                            <td>
                                0
                            </td>
                            <td>
                                D
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h5>Keterampilan</h5>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-sm">
                <thead>
                    <tr>
                        <th rowspan="2">No</th>
                        <th rowspan="2">NIPD</th>
                        <th rowspan="2">Nama</th>
                        <th colspan="{{data_mapel[1]|length}}">Kompetensi Dasar</th>
                        <th colspan="4">Nilai</th>
                    </tr>
                    <tr>
                        {% for item in data_mapel[1] %}
                        <th>{{item[0]}}</th>
                        {% endfor %}
                        <th>Rata-rata</th>
                        <th>Predikat</th>
                        <th>Maksimal</th>
                        <th>Minimal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in siswa -%}
                        <tr>
                            <td>
                                {{loop.index}}
                            </td>
                            <td>
                                {{item[0]}}
                            </td>
                            <td>
                                {{item[2]}}
                            </td>
                            {% for kd in data_mapel[1] %}
                            <td>
                                <input type="number" name="{{item[0]}}" value="0"/>
                            </td>
                            {% endfor %}
                            <td>
                                0
                            </td>
                            <td>
                                D
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <input type="submit" class="btn btn-success" value="Simpan">
    </form>

{% endblock %}